<?php

/**
 * Implements hook_menu()
 */
function assessment_node_engine_menu() {
  $items['my-node-system/add-node'] = array(
    'title' => t("Add new Article"),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'file' => 'assessment_node_engine.form.inc',
    'access callback' => 'assessment_node_engine_confirm_access',
    'access arguments' => array("create", $GLOBALS['user']),
  );

  /* $items['my-node-system/%'] = array(
  ); */

  return $items;
}

/**
 * Implements hook_theme()
 */
function assessment_node_engine_theme($existing, $type, $theme, $path) {
  return array(
    'article' => array(
      'template' => 'article',
      'variables' => array(
        'created' => NULL,
        'changed' => NULL,
        'title' => NULL,
        'bodytext' => NULL,
      )
    ),
  );
}

/**
 * Confirms the user has access to the feature. This could be implemented using
 * the 'access arguments' setting but I was not clear on if we needed to
 * reimplement.
 */
function assessment_node_engine_confirm_access($op, $account) {
  if(user_access('administer nodes', $account)) {
    return TRUE;
  } else {
    return FALSE;
  }
}

/**
 * Creates a new article item
 */
